name: Vault Creation
on:
 workflow_dispatch:
    inputs:
      Team_Name:
        description: Terraform Workspaces
        required: false
        #default: devsecops-test
        type: choice
        options:
        - dso-sandbox
        - dso-test
        - devsecops-test
        - learning
        - devsecops
        - cloudops
        - kip-prod
        - kip-uat
        - conn-tech-sbox
        - tax-client
        - informatica
        - icas
        - culture-snap
        - pxcube
        - modelling
        - fmmicros
        - chrisastley
        - ukfmtis
        - tax-technology
        - enterprise-bey
        - digital-uk
        - ctc-portal
        - helios
        - btmobile
        - pccportal
        - tax-coe-b2c
        - fizznunwood
        - culture-snap-dev
        - kclientazure
      
      # task:
      #   description: Task to be done 
      #   required: false
      #   #default: deploy
      #   type: choice
      #   options:
      #   - deploy

      region:
        description: Region to be selected
        #required: false
        default: uk-south
        type: choice
        options:
        - uk-south
        - uk-west
      
      location:
        description: Location to be selected
        #required: false
        default: UK South
        type: choice
        options:
        - UK South
        - UK West

      Subscription_Name:
        description: Name of the Subscription
        required: false
        type: string

      Subscription_Id:
        description: Subscription Id
        required: false
        type: string

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: deploy

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Echo commands
        if: ${{  inputs.task == 'deploy_lighthouse' }} 
        run: |
            echo "hello"
            echo ${{ inputs.task }}
            echo ${{ inputs.Subscription_Name }}
